### ISSUE TITLE
After update to version 1.8, But still No appeared of power factor data or MQTT

### ISSUE THREAD

**Issue by riahtu** [lewei50/iammeter-docker#14]
After update to version 1.8, Why still no appeared of power factor data or MQTT setting feature?
![screenshot-202 129 205 3_5050-2021 06 23-10_08_16](https://user-images.githubusercontent.com/315150/123029814-e95f5580-d40b-11eb-892d-1467e1b0e153.png)
![screenshot-202 129 205 3_5050-2021 06 23-10_08_54](https://user-images.githubusercontent.com/315150/123029824-ec5a4600-d40b-11eb-8ae9-5344471b882f.png)

**Comment by guanvee** [comment]
Only three-phase meters have pf data, please confirm the meter type.

**Comment by riahtu** [comment]
OK, I see. 

Thank you.
Uthai Roemtrakul

**Comment by lewei50** [comment]
solved

**Comment by lewei50** [comment]
solved
