### ISSUE TITLE
How to increase the meter count limit?

### ISSUE THREAD

**Issue by riahtu** [lewei50/iammeter-docker#7]
Docker has limit number of meter to 10 ., may I know how to changing a number of meter count?

**Comment by lewei50** [comment]
Hi, 
For some reason ,we limit the meter number in our free local system.
if you need more quantity ,please contact our colleague Steven.lu(steven.lu@devicebit.com) , he will help you .

**Comment by riahtu** [comment]
Thank you, lewei50.
