### ISSUE TITLE
Double CT calculation problem differrent result between iammeter docker versioin and iammeter cloud version 

### ISSUE THREAD

**Issue by riahtu** [lewei50/iammeter-docker#8]
I found problem about Double CT calculation,  select the same ct ratio and same iMeter device but result differrent,

IAMMETER Cloud version (iammeter web) setting CT ratio: 
![screenshot-www iammeter com-2021 04 28-17_40_32](https://user-images.githubusercontent.com/315150/116566079-a19edf00-a930-11eb-830a-86f867e174aa.png)

IAMMETER Docker version (local install) setting CT ratio:
![screenshot-2021 04 28-17_40_11](https://user-images.githubusercontent.com/315150/116566126-af546480-a930-11eb-9b93-8374e754e317.png)

IAMMETER Cloud version (iammeter web) calculation result:
![screenshot-www iammeter com-2021 04 28-17_38_37](https://user-images.githubusercontent.com/315150/116566199-c09d7100-a930-11eb-9d20-e207c8b195c2.png)

IAMMETER Docker version (local install) calculation result:
![screenshot-2021 04 28-17_38_20](https://user-images.githubusercontent.com/315150/116566242-cb580600-a930-11eb-8037-d7e95030caad.png)

**Comment by lewei50** [comment]
Hi ,the problem have been solved in the latest version(1.6)
please refer to https://imeter.club/topic/10

**Comment by riahtu** [comment]
Thank you, lewei50.
